import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/backend";

// Local types mirror the external LoomTrack schema (source of truth).
// UUID `id` is internal only; the *_no / record_no fields are the user-facing IDs (generated by the database).
export type Business = {
  id: string; business_no: number; company_name: string; address: string; phone: string;
  email: string | null; city: string | null; state: string | null; country: string | null;
  postal_code: string | null; tax_id: string | null; is_active: boolean;
};
export type Membership = {
  id: string; business_user_no: number; business_id: string; user_id: string; role: string; is_active: boolean;
  businesses: Business | null;
};
export type Machine = { id: string; record_no: number; business_id: string; name: string; is_active: boolean };
export type Product = { id: string; record_no: number; business_id: string; name: string; code: string; default_piece_rate: number; unit: string; is_active: boolean };
export type Employee = { id: string; record_no: number; business_id: string; name: string; phone: string | null; join_date: string | null; is_active: boolean };
export type Customer = { id: string; record_no: number; business_id: string; name: string; phone: string | null; address: string | null; is_active: boolean };
export type Direction = "INCOME" | "EXPENSE";
export type ProductionEntry = {
  id: string; record_no: number; business_id: string; production_date: string; machine_id: string; product_id: string;
  employee_id: string; quantity: number; piece_rate: number; wage_amount: number; notes: string | null; created_at: string;
};

export function useProductionEntries(from: string, to: string) {
  const bid = useBusinessId();
  return useQuery({
    queryKey: ["production_entries", bid, from, to],
    enabled: !!bid,
    queryFn: async () => {
      const { data, error } = await db.from("production_entries").select("*").eq("business_id", bid)
        .gte("production_date", from).lte("production_date", to)
        .order("production_date", { ascending: false }).order("created_at", { ascending: false }).limit(5000);
      if (error) throw error;
      return data as ProductionEntry[];
    },
  });
}
/** Latest N production entries for the current business, newest first. */
export function useRecentProduction(limit = 5) {
  const bid = useBusinessId();
  return useQuery({
    queryKey: ["production_entries", bid, "recent", limit],
    enabled: !!bid,
    queryFn: async () => {
      const { data, error } = await db.from("production_entries").select("*").eq("business_id", bid)
        .order("production_date", { ascending: false }).order("created_at", { ascending: false }).limit(limit);
      if (error) throw error;
      return data as ProductionEntry[];
    },
  });
}
export type PaymentType = { id: string; payment_type_no: number; business_id: string | null; description: string; direction: Direction; is_active: boolean };
export type Payment = {
  id: string; payment_no: number; business_id: string; payment_date: string; payment_type_id: string;
  amount: number; employee_id: string | null; description: string | null; created_at: string;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const db = supabase as any;

export async function fetchMembership(): Promise<Membership | null> {
  const { data: u } = await supabase.auth.getUser();
  if (!u.user) return null;
  const { data, error } = await db.from("business_users")
    .select("id,business_user_no,business_id,user_id,role,is_active,businesses(*)")
    .eq("user_id", u.user.id).eq("is_active", true).order("created_at").limit(1).maybeSingle();
  if (error) throw error;
  return data as Membership | null;
}

export const useMembership = () => useQuery({ queryKey: ["membership"], queryFn: fetchMembership, staleTime: 60_000 });

/** Current business id; every business query below is scoped to it. */
export function useBusinessId() {
  return useMembership().data?.business_id;
}

function useScoped<T>(key: string, table: string, order: string) {
  const bid = useBusinessId();
  return useQuery({
    queryKey: [table, bid, key],
    enabled: !!bid,
    queryFn: async () => {
      const { data, error } = await db.from(table).select("*").eq("business_id", bid).order(order);
      if (error) throw error;
      return data as T[];
    },
  });
}

export const useMachines = () => useScoped<Machine>("all", "machines", "name");
export const useProducts = () => useScoped<Product>("all", "products", "name");
export const useEmployees = () => useScoped<Employee>("all", "employees", "name");
export const useCustomers = () => useScoped<Customer>("all", "customers", "name");

// Standard seeded types may be shared (business_id null) or per-business.
export function usePaymentTypes() {
  const bid = useBusinessId();
  return useQuery({
    queryKey: ["payment_types", bid],
    enabled: !!bid,
    queryFn: async () => {
      const { data, error } = await db.from("payment_types").select("*")
        .or(`business_id.eq.${bid},business_id.is.null`).order("payment_type_no");
      if (error) throw error;
      return data as PaymentType[];
    },
  });
}

export function usePayments(from: string, to: string) {
  const bid = useBusinessId();
  return useQuery({
    queryKey: ["payments", bid, from, to],
    enabled: !!bid,
    queryFn: async () => {
      const { data, error } = await db.from("payments").select("*").eq("business_id", bid)
        .gte("payment_date", from).lte("payment_date", to)
        .order("payment_date", { ascending: false }).order("created_at", { ascending: false }).limit(5000);
      if (error) throw error;
      return data as Payment[];
    },
  });
}

export function useSettings() {
  const m = useMembership();
  return { ...m, data: m.data ? { business_name: m.data.businesses?.company_name ?? "", currency: "₹" } : undefined };
}

export function useInvalidateAll() {
  const qc = useQueryClient();
  return () => qc.invalidateQueries();
}

export function nameMap<T extends { id: string; name: string }>(list?: T[]) {
  const m: Record<string, string> = {};
  list?.forEach((x) => (m[x.id] = x.name));
  return m;
}

export function sum<T>(list: T[] | undefined, f: (x: T) => number) {
  return (list ?? []).reduce((a, x) => a + Number(f(x) || 0), 0);
}

export function errMsg(e: unknown) {
  if (e && typeof e === "object" && "message" in e) return String((e as { message: string }).message);
  return "Something went wrong";
}
